"""rename department

Revision ID: 86882bdff90c
Revises: db6575087820
Create Date: 2023-11-20 02:57:05.321488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86882bdff90c'
down_revision = 'db6575087820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
